version: '2'
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    volumes:
      - .:/app
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
     - db
     - redis
volumes:
  data: