default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 40
  timeout: 5000

development:
  <<: *default
  database: filmplanner_development

test:
  <<: *default
  database: filmplanner_test
