default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: filmplanner_admin
  password: welkom123

development:
  <<: *default
  database: filmplanner_development

test:
  <<: *default
  database: filmplanner_test
