---
:concurrency: 20
:queues:
  - critical
  - default
  - low
:schedule:
  sync_theaters:
    cron: '0 0 * * 0'
    class: TheaterSynchronizeWorker
    description: 'Synchronize all theaters of Pathe.nl to our own database'
  sync_schedule:
    cron: '0 0 * * 2'
    class: ScheduleSynchronizeWorker
    description: 'Synchronize movies and shows of all Pathe.nl theaters to our own database'