---
:concurrency: 20
:queues:
  - critical
  - default
  - low
:schedule:
  pathe_sync_theaters:
    cron: '0 0 * * 0'
    class: Pathe::TheaterSynchronizeWorker
    description: 'Synchronize all theaters of Pathe.nl to our own database'
  pathe_sync_schedule:
    cron: '0 0 * * 2'
    class: Pathe::ScheduleSynchronizeWorker
    description: 'Synchronize movies and shows of all Pathe.nl theaters to our own database'